# Generated by Django 4.2.4 on 2023-08-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_remove_book_available_copies'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available_copies',
            field=models.PositiveBigIntegerField(default=10),
            preserve_default=False,
        ),
    ]
