# Generated by Django 4.2.4 on 2023-08-16 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_book_available_copies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowingrecord',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 15, 12, 27, 24, 759230)),
        ),
    ]
